	tilepal 0, GRAY, GREEN, BROWN, RED, GREEN, BROWN, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN, GREEN, GREEN
	tilepal 0, ROOF, ROOF, ROOF, GRAY, WATER, ROOF, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, ROOF, ROOF, ROOF, BROWN, BROWN, BROWN, BROWN, GRAY
	tilepal 0, GRAY, GRAY, GRAY, BROWN, GREEN, BROWN, BROWN, GREEN
	tilepal 0, ROOF, ROOF, ROOF, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GREEN, GREEN, GREEN, BROWN, BROWN, GREEN
	tilepal 0, BROWN, RED, BROWN, BROWN, GRAY, GRAY, GRAY, BROWN
	tilepal 0, BROWN, BROWN, GREEN, GREEN, GRAY, GRAY, GRAY, RED
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, WATER

rept 16
	db $ff
endr

	tilepal 1, WATER, WATER, GRAY, RED, GREEN, BROWN, GRAY, GRAY
	tilepal 1, GREEN, GREEN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, WATER, WATER, RED, GRAY, WATER, ROOF, GRAY, GRAY
	tilepal 1, GREEN, GREEN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, GREEN, GREEN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 1, GREEN, GREEN, GRAY, BROWN, GREEN, BROWN, BROWN, GREEN
	tilepal 1, GREEN, GREEN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, GRAY, GRAY, GREEN, GREEN, GREEN, BROWN, BROWN, GREEN
	tilepal 1, GREEN, GREEN, BROWN, BROWN, BROWN, BROWN, BROWN, YELLOW
	tilepal 1, YELLOW, BROWN, GREEN, GREEN, WATER, WATER, WATER, RED
	tilepal 1, GREEN, GREEN, YELLOW, BROWN, GRAY, GRAY, GRAY, BROWN
	tilepal 1, BROWN, TEXT
